import { FeedSourceConfig } from "@/types";

export const RSS_SOURCES: FeedSourceConfig[] = [
  // ── AI & ML News ──
  {
    id: "verge-ai",
    name: "The Verge - AI",
    url: "https://www.theverge.com/rss/ai-artificial-intelligence/index.xml",
    type: "rss",
    category: "ai",
    icon: "▲",
    color: "#6366f1",
    enabled: true,
  },
  {
    id: "techcrunch-ai",
    name: "TechCrunch - AI",
    url: "https://techcrunch.com/category/artificial-intelligence/feed/",
    type: "rss",
    category: "ai",
    icon: "TC",
    color: "#22c55e",
    enabled: true,
  },
  {
    id: "ars-ai",
    name: "Ars Technica - AI",
    url: "https://feeds.arstechnica.com/arstechnica/technology-lab",
    type: "rss",
    category: "ai",
    icon: "Ars",
    color: "#f97316",
    enabled: true,
  },
  {
    id: "mit-tech",
    name: "MIT Tech Review",
    url: "https://www.technologyreview.com/feed/",
    type: "rss",
    category: "ai",
    icon: "MIT",
    color: "#a855f7",
    enabled: true,
  },
  {
    id: "wired-ai",
    name: "Wired",
    url: "https://www.wired.com/feed/rss",
    type: "rss",
    category: "ai",
    icon: "W",
    color: "#ec4899",
    enabled: true,
  },
  {
    id: "venturebeat-ai",
    name: "VentureBeat - AI",
    url: "https://venturebeat.com/category/ai/feed/",
    type: "rss",
    category: "ai",
    icon: "VB",
    color: "#14b8a6",
    enabled: true,
  },

  // ── Gaming News ──
  {
    id: "ign",
    name: "IGN",
    url: "https://feeds.feedburner.com/ign/all",
    type: "rss",
    category: "gaming",
    icon: "IGN",
    color: "#ef4444",
    enabled: true,
  },
  {
    id: "kotaku",
    name: "Kotaku",
    url: "https://kotaku.com/rss",
    type: "rss",
    category: "gaming",
    icon: "K",
    color: "#f59e0b",
    enabled: true,
  },
  {
    id: "pcgamer",
    name: "PC Gamer",
    url: "https://www.pcgamer.com/rss/",
    type: "rss",
    category: "gaming",
    icon: "PCG",
    color: "#ef4444",
    enabled: true,
  },
  {
    id: "eurogamer",
    name: "Eurogamer",
    url: "https://www.eurogamer.net/feed",
    type: "rss",
    category: "gaming",
    icon: "EG",
    color: "#6366f1",
    enabled: true,
  },
  {
    id: "polygon",
    name: "Polygon",
    url: "https://www.polygon.com/rss/index.xml",
    type: "rss",
    category: "gaming",
    icon: "P",
    color: "#f59e0b",
    enabled: true,
  },
  {
    id: "gamespot",
    name: "GameSpot",
    url: "https://www.gamespot.com/feeds/mashup/",
    type: "rss",
    category: "gaming",
    icon: "GS",
    color: "#22c55e",
    enabled: true,
  },
  {
    id: "rps",
    name: "Rock Paper Shotgun",
    url: "https://www.rockpapershotgun.com/feed",
    type: "rss",
    category: "gaming",
    icon: "RPS",
    color: "#06b6d4",
    enabled: true,
  },

  // ── General Tech ──
  {
    id: "verge",
    name: "The Verge",
    url: "https://www.theverge.com/rss/index.xml",
    type: "rss",
    category: "general",
    icon: "▲",
    color: "#6366f1",
    enabled: false,
  },
  {
    id: "arstechnica",
    name: "Ars Technica",
    url: "https://feeds.arstechnica.com/arstechnica/index",
    type: "rss",
    category: "general",
    icon: "Ars",
    color: "#f97316",
    enabled: false,
  },
];

export const REDDIT_SOURCES: FeedSourceConfig[] = [
  // AI subreddits
  {
    id: "r-artificial",
    name: "r/artificial",
    url: "https://www.reddit.com/r/artificial.json?limit=25",
    type: "reddit",
    category: "ai",
    icon: "🤖",
    color: "#6366f1",
    enabled: true,
  },
  {
    id: "r-machinelearning",
    name: "r/MachineLearning",
    url: "https://www.reddit.com/r/MachineLearning.json?limit=25",
    type: "reddit",
    category: "ai",
    icon: "🧠",
    color: "#a855f7",
    enabled: true,
  },
  {
    id: "r-openai",
    name: "r/OpenAI",
    url: "https://www.reddit.com/r/OpenAI.json?limit=25",
    type: "reddit",
    category: "ai",
    icon: "🔮",
    color: "#22c55e",
    enabled: true,
  },
  {
    id: "r-localllama",
    name: "r/LocalLLaMA",
    url: "https://www.reddit.com/r/LocalLLaMA.json?limit=25",
    type: "reddit",
    category: "ai",
    icon: "🦙",
    color: "#14b8a6",
    enabled: true,
  },
  {
    id: "r-singularity",
    name: "r/singularity",
    url: "https://www.reddit.com/r/singularity.json?limit=25",
    type: "reddit",
    category: "ai",
    icon: "🌀",
    color: "#ec4899",
    enabled: true,
  },
  // Gaming subreddits
  {
    id: "r-games",
    name: "r/Games",
    url: "https://www.reddit.com/r/Games.json?limit=25",
    type: "reddit",
    category: "gaming",
    icon: "🎮",
    color: "#22c55e",
    enabled: true,
  },
  {
    id: "r-pcgaming",
    name: "r/pcgaming",
    url: "https://www.reddit.com/r/pcgaming.json?limit=25",
    type: "reddit",
    category: "gaming",
    icon: "🖥️",
    color: "#6366f1",
    enabled: true,
  },
  {
    id: "r-gaming",
    name: "r/gaming",
    url: "https://www.reddit.com/r/gaming.json?limit=25",
    type: "reddit",
    category: "gaming",
    icon: "🕹️",
    color: "#ef4444",
    enabled: true,
  },
  {
    id: "r-gamernews",
    name: "r/gamernews",
    url: "https://www.reddit.com/r/gamernews.json?limit=25",
    type: "reddit",
    category: "gaming",
    icon: "📰",
    color: "#f59e0b",
    enabled: true,
  },
];

export const HACKERNEWS_SOURCE: FeedSourceConfig = {
  id: "hackernews",
  name: "Hacker News",
  url: "https://hacker-news.firebaseio.com/v0",
  type: "hackernews",
  category: "general",
  icon: "HN",
  color: "#f97316",
  enabled: true,
};

export const BLUESKY_SOURCE: FeedSourceConfig = {
  id: "bluesky",
  name: "Bluesky",
  url: "https://public.api.bsky.app",
  type: "bluesky",
  category: "social",
  icon: "BS",
  color: "#0085ff",
  enabled: true,
};

export const GITHUB_SOURCE: FeedSourceConfig = {
  id: "github-trending",
  name: "GitHub Trending",
  url: "https://api.github.com",
  type: "github",
  category: "ai",
  icon: "GH",
  color: "#8b5cf6",
  enabled: true,
};

export const STEAM_SOURCE: FeedSourceConfig = {
  id: "steam-news",
  name: "Steam News",
  url: "https://api.steampowered.com",
  type: "steam",
  category: "gaming",
  icon: "ST",
  color: "#1b2838",
  enabled: true,
};

export function getAllEnabledSources(): FeedSourceConfig[] {
  return [
    ...RSS_SOURCES.filter((s) => s.enabled),
    ...REDDIT_SOURCES.filter((s) => s.enabled),
    ...(HACKERNEWS_SOURCE.enabled ? [HACKERNEWS_SOURCE] : []),
    ...(BLUESKY_SOURCE.enabled ? [BLUESKY_SOURCE] : []),
    ...(GITHUB_SOURCE.enabled ? [GITHUB_SOURCE] : []),
    ...(STEAM_SOURCE.enabled ? [STEAM_SOURCE] : []),
  ];
}
